### ISSUE TITLE
Adapt toolchain to demo script

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/insurance-toolchain#2]
Change toolchain so that:
- [x] All 9 microservices deploy into a single space (the one that the user is logged into). Services will have different name prefixes. Example:
- dev-{service-name}
- test-{service-name}
- {service-name}
- [x] Remove slack integration (will be added interactively during the demo)

**Comment by jakepeyser** [comment]
Ok so I had to change quite a bit to make this work as desired. Here is the gist of it:
- Consolidated Delivery Pipeline inputs during toolchain creation step into a single set of region/org/space inputs. All apps now deploy into this location
- To isolate datastores, I configured each set of apps to have it's own `policy-db`. In order to do this, I had to do a dynamic lookup within the Catalog and Orders microservices. I also had to remove `policy-db` from the `manifest.yml` file of both apps as it caused a binding error on app startup. In order to compensate for this, we now push the apps with the `--no-start` option, bind the corresponding db service, and then start the apps
- All Catalog app instances still use a single instance of Tradeoff Analytics as there is no reason to create three separate instances for a non-corpus-based Watson service

@uwefassnacht: please create a new `insurance` toolchain with your credentials and verify that everything works as expected
